Display/urls.py
from django.conf.urls import url, include
from Display import views

urlpatterns = [

]

Music/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from Display import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name="HomePage"),
    url(r'^(?P<arg>[a-z]+)/(?P<id>[0-9]+)/$', views.Detail, name="Detail"),
    url(r'^make_request/$', views.make_request, name="RequestForm"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Display/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Genre(models.Model):
    Name = models.CharField(max_length=50)
    Details = models.TextField()
    Logo = models.FileField(null=True , blank=True)
    def __str__(self):
        return self.Name

class Artist(models.Model):
    ArtistName = models.CharField(max_length=200)
    Bio = models.TextField()
    Picture = models.FileField()
    def __str__(self):
        return self.ArtistName

class Song(models.Model):
    Artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    Genre  = models.ForeignKey(Genre, on_delete=models.CASCADE)
    Album = models.CharField(max_length=200 ,null=False)
    Title = models.CharField(max_length=50, null=False)
    IntroDetails = models.TextField(null=True)
    Verse1Details = models.TextField(null=True)
    Verse2Details = models.TextField(null=True)
    OutroDetails = models.TextField(null=True)
    Image_src = models.FileField()
    def __str__(self):
        return self.Title

class Request(models.Model):
    Song_name = models.CharField(max_length=200)
    Artist = models.CharField(max_length=100 ,null=True , blank=True)
    Message = models.TextField(null=True , blank=True)
    def __str__(self):
        return self.Song_name
class Author_request(models.Model):
    Name = models.CharField(max_length=200)
    Email = models.EmailField()
    Verification = models.BooleanField()

Display/forms.py
from django import forms


from models import Request,Author_request,Song


class Request_form(forms.ModelForm):
    class Meta:
        model = Request
        fields = [
            "Song_name",
            "Artist",
            "Message",
        ]


class Author_request_form(forms.ModelForm):
    class Meta:
        model = Author_request
        fields = [
            "Name",
            "Email",
        ]


class Song_form(forms.ModelForm):
    class Meta:
        model = Song
        fields = [
            "Artist",
            "Genre",
            "Album",
            "Title",
            "Image_src",
            "IntroDetails",
            "Verse1Details",
            "Verse2Details",
            "OutroDetails",
        ]

Display/views.py
from django.shortcuts import render,get_object_or_404 , redirect
from .models import Song , Genre, Artist, Request
from  django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib import messages
from forms import Request_form
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def index(request):
    song_argument = (Song.objects.latest('id').id) - 3
    artist_argument = (Artist.objects.latest('id').id) - 3
    genre_argument = (Genre.objects.latest('id').id) - 3
    Songs = Song.objects.filter(id__gte=song_argument)
    Genres = Genre.objects.filter(id__gte=genre_argument)
    Artists = Artist.objects.filter(id__gte=artist_argument)
    rqst = request.GET.get('query')
    context = {}
    if rqst:
        form = Request_form(request.POST or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return HttpResponseRedirect("/")
        context.update({"form":form,})
        Songs = Song.objects.filter(Title__icontains=rqst)
        Genres = Genre.objects.filter(Name__icontains=rqst)
        Artists = Artist.objects.filter(ArtistName__icontains=rqst)
    context.update({
        "check" : rqst,
        "songs" : Songs,
        "genres":Genres,
        "Artist":Artists,
    })
    return render(request, 'index.html',context)

def Detail(request , arg ,id):
    if arg == 'a':
        artist = get_object_or_404(Artist, id=id)
        print arg
        context = {
            "artist": artist,
            "chck": arg,
            "chck2": len(arg),
        }
        return render(request, 'Details.html', context)
    elif arg == 'g':
        genre = get_object_or_404(Genre, id=id)
        context = {
            "genre": genre,
            "chck": arg,

            "chck2": len(arg),
        }
        return render(request, 'Details.html', context)
    elif arg == 's':
        song = get_object_or_404(Song, id=id)
        context = {
            "song" : song,
            "chck" : arg,

            "chck2": len(arg),
        }
        return render(request , 'Details.html' , context)
    elif arg == 'ss':
        song_list = Song.objects.all()
        paginator = Paginator(song_list, 3)  # Show 25 contacts per page
        page = request.GET.get('page')


        page = request.GET.get('page')
        try:
            song_list = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            song_list = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            song_list = paginator.page(paginator.num_pages)

        context = {
            "songs": song_list,
            "chck": arg,
            "chck2": len(arg),
        }
        return render(request, 'Details.html', context)
    elif arg == 'gs':
        genre_list = Genre.objects.all()
        paginator = Paginator(genre_list, 3)  # Show 25 contacts per page
        page = request.GET.get('page')


        page = request.GET.get('page')
        try:
            genre_list = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            genre_list = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            genre_list = paginator.page(paginator.num_pages)

        context = {
            "genres": genre_list,
            "chck": arg,
            "chck2": len(arg),
        }
        return render(request, 'Details.html', context)
    elif arg == 'as':
        artist_list = Artist.objects.all()
        paginator = Paginator(artist_list, 3)  # Show 25 contacts per page
        page = request.GET.get('page')

        page = request.GET.get('page')
        try:
            artist_list = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            artist_list = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            artist_list = paginator.page(paginator.num_pages)

        context = {
            "artists": artist_list,
            "chck": arg,
            "chck2": len(arg),
        }
        return render(request, 'Details.html', context)

def make_request(request):
    form = Request_form(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return redirect(to="/")


    context = {
        "form": form,
    }
    return render(request, "Make_request.html", context)

templates/Details.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail View<!--{%if chck == 's'%}{{ song.Title }}{%elif chck == 's'%}{{ song.Title }}{%elif chck == 's'%}{{ song.Title }}{% endif %}--></title>

      <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.9";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div id="main_body">
    <div id="load_screen">
        LOADING
        <div id="big_sqr">
            <div id="sqr1"></div>
            <div id="sqr2"></div>
            <div id="sqr3"></div>
            <div id="sqr4"></div>
        </div>
    </div>
</div>
<script>
    window.addEventListener("load", function loader () {
        var load_screen = document.getElementById("load_screen");
        var bckg = document.getElementById("main_body");
        document.body.removeChild(bckg);
        document.body.removeChild(load_screen);
    })
</script>
<header>
    <nav>
		<ul>

			<li class="frst">
				Our Blog
			</li>
            <li class="frst">
				About
			</li>
            <a href="{% url 'HomePage' %}"><li class="frst">
				Home
			</li></a>
		</ul>
	</nav>
    <div id="branding">

        <h1>How Music is Made</h1>

        <span>Welcome to Music Analysis</span>

        <form method='GET' action=''>
        <input id = "search" type="text" name = 'query' placeholder="Search for Song, Artist or Album"/>
        </form>
        <svg class="arrows">
            <path class="a1" d="M0 0 L30 32 L60 0"></path>
            <path class="a2" d="M0 20 L30 52 L60 20"></path>
            <path class="a3" d="M0 40 L30 72 L60 40"></path>
        </svg>
    </div>
</header>
{% if chck2 == 1 %}
<div id="detailcontainer">
    {% if chck == 's' %}
    <div>
        <img src = "{{ song.Image_src.url }}" />
        {{ song.Title }}<br/><br/><br/>

        {{ song.Album }}<br/><br/><br/>

        {{ song.IntroDetails }}<br/><br/><br/>

        {{ song.Verse1Details }}<br/><br/><br/>

        {{ song.Verse2Details }}<br/><br/><br/>
    </div>
    {% endif %}

    {% if chck == 'a' %}

    <div>
        <img src = "{{ artist.Picture.url }}" />

        {{ artist.ArtistName }}<br/><br/><br/>

        {{ artist.Bio }}<br/><br/><br/>
    </div>
    {% endif %}
    {% if chck == 'g' %}
    <div>
        <img src = "{{ genre.Logo.url }}" />

        {{ genre.Name }}<br/><br/><br/>

        {{ genre.Details }}<br/><br/><br/>

    </div>
    {% endif %}
<div class="fb-like" data-href="{{request.build_absolute_url}}" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div><br/>
<div class="fb-comments" data-href="{{request.build_absolute_url}}" data-numposts="5"></div>
</div>
{% endif %}
    {% if chck == 'ss' %}
        {% for song in songs %}}
            <a href="{% url 'Detail' arg='s' id=song.id%}"><div class="browse">
                <img src = "{{ song.Image_src.url }}" />
                <p><span>Name</span><span id="colon">:</span>{{ song.Title }}<br/></p>
                <p><span>Artist</span><span id="colon">:</span>{{ song.Artist.ArtistName }}</p>
                <p><span>Album</span><span id="colon">:</span>{{ song.Album }}<br/></p>
                <p><span>Genre</span><span id="colon">:</span>{{ song.Genre.Name }}</p>
            </div></a>
        {% endfor %}

    <div class="pagination">
            {% if songs.has_previous %}
                <a href="?page={{ songs.previous_page_number }}">Previous</a>
            {% endif %}

            <span id="paginator">
                Page {{ songs.number }} of {{ songs.paginator.num_pages }}.
            </span>

            {% if songs.has_next %}
                <a href="?page={{ songs.next_page_number }}">Next</a>
            {% endif %}
    </div>
{% endif %}
{% if chck == 'gs' %}
    {% for genre in genres %}
        <a href="{% url 'Detail' arg='g' id=genre.id%}"><div class="browse">
            <img src = "{{ genre.Logo.url }}" />

            <p>{{ genre.Name }}<br/></p>

            <p>{{ genre.Details | truncatechars:200}}<br/></p>

        </div></a>
    {% endfor %}

    <div class="pagination">
        {% if genres.has_previous %}
            <a href="?page={{ genres.previous_page_number }}">Previous</a>
        {% endif %}

        <span id="paginator_left">
            Page {{ genres.number }} of {{ genres.paginator.num_pages }}.
        </span>

        {% if genres.has_next %}
            <a href="?page={{ genres.next_page_number }}">Next</a>
        {% endif %}
    </div>
{% endif %}
{% if chck == 'as' %}
    {% for artist in artists %}
        <a href="{% url 'Detail' arg='a' id=artist.id%}"><div class="browse">
            <img src = "{{ artist.Picture.url }}" />

            <p>{{ artist.ArtistName }}</p><br/>

            <p>{{ artist.Bio |truncatechars:200  }}</p><br/>
        </div></a>
    {% endfor %}

<div class="pagination">
        {% if artists.has_previous %}
            <a href="?page={{ artists.previous_page_number }}">Previous</a>
        {% endif %}

        <span id="paginator">
            Page {{ artists.number }} of {{ artists.paginator.num_pages }}.
        </span>

        {% if artists.has_next %}
            <a href="?page={{ artists.next_page_number }}">Next</a>
        {% endif %}
</div>
{% endif %}

<footer>
    <!--Stuff for footer here-->
    <h1>Stay Connected</h1><h1>Music_Analysis Group Copyright &copy;2017 </h1>
    <div class="social-btns"><a class="btn facebook" href="#"><i class="fa fa-facebook"></i></a><a class="btn twitter" href="#"><i class="fa fa-twitter"></i></a><a class="btn google" href="#"><i class="fa fa-google"></i></a></div>

</footer>

</body>
</html>

templates/Make_request.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Make a Request</title>
</head>
<body>
    <form method='POST' action=''>{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Music Analysis</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>

<div id="load_screen">
    LOADING
    <div id="big_sqr">
        <div id="sqr1"></div>
        <div id="sqr2"></div>
        <div id="sqr3"></div>
        <div id="sqr4"></div>
    </div>
</div>
<div id="main_body">
    <div id="load_screen">
        LOADING
        <div id="big_sqr">
            <div id="sqr1"></div>
            <div id="sqr2"></div>
            <div id="sqr3"></div>
            <div id="sqr4"></div>
        </div>
    </div>
</div>
<script>
    window.addEventListener("load", function loader () {
        var load_screen = document.getElementById("load_screen");
        var bckg = document.getElementById("main_body");
        document.body.removeChild(bckg);
        document.body.removeChild(load_screen);
        document.getElementById("main").style.display='block';
    })
</script>
<div id="main">
<header>
    <nav>
		<ul>

			<li class="frst">
				Our Blog
			</li>
            <li class="frst">
				About
			</li>
            <a href="{% url 'HomePage' %}"><li class="frst">
				Home
			</li></a>
		</ul>
	</nav>
    <div id="branding">

        <h1>How Music is Made</h1>

        <span>Welcome to Music Analysis</span>

        <form method='GET' action=''>
        <input id = "search" type="text" name = 'query' placeholder="Search for Song, Artist or Album"/>
        </form>
        <svg class="arrows">
            <path class="a1" d="M0 0 L30 32 L60 0"></path>
            <path class="a2" d="M0 20 L30 52 L60 20"></path>
            <path class="a3" d="M0 40 L30 72 L60 40"></path>
        </svg>
    </div>
</header>
<!--If search is not done-->
{% if not check %}
<section id="container">
    <p id="wait">
        We are tailors of brand experiences, creating intelligent solutions with good people. We team up with our clients to help them put their best face forward and authentically communicate their offering to the world. We believe in prototyping, taking risks, and building meaningful work that surprises and achieves measurable results.
        Our team is close-knit and collaborative, with an extensive offering of services and a commitment to surpassing client expectations. An interconnected team means that we each play a part in every project that comes through our doors, and that we feel pride and ownership in everything we do.
    </p>
    <div class="collection">
    <a href="ss/{{ 1 }}"><div id="button">See Songs</div></a>
    {% for song in songs %}
        <a href="s/{{ song.id }}">
            <div class="Songs">
                <img src = "{{ song.Image_src.url }}" />
                <p>{{song.Title}}</p>
                <p>{{song.Artist.ArtistName}}</p>

            </div>
        </a>
    {% endfor %}
    </div>
    <a href="as/{{ 1 }}"><div id="button">See Artist</div></a>
    <div class="collection">
    {% for artist in Artist %}
        <a href="a/{{ artist.id }}">
            <div class="Songs">
                <img src = "{{ artist.Picture.url }}" />
                <p>{{artist.ArtistName}}</p>
                <p>{{artist.Bio | truncatechars:150}}</p>
            </div>
        </a>
    {% endfor %}
    </div>
    <div class="collection">
    <a href="gs/{{ 1 }}"><div id="button">See Genres</div></a>
    {% for genre in genres %}
        <a href="g/{{ genre.id }}">
            <div class="Songs">
                <img src = "{{ genre.Logo.url }}" />
                <p>{{genre.Name}}</p>
                <p>{{genre.Details | truncatechars:150}}</p>
            </div>
        </a>
    {% endfor %}
</div>
{% endif %}

<!--If search is done-->

{% if check %}
    {% for song in songs %}
        <a href="{% url 'Detail' arg='s' id=song.id%}"><div class="browse">
            <img src = "{{ song.Image_src.url }}" />
            <p><span>Name</span><span id="colon">:</span>{{ song.Title }}<br/></p>
            <p><span>Artist</span><span id="colon">:</span>{{ song.Artist.ArtistName }}</p>
            <p><span>Album</span><span id="colon">:</span>{{ song.Album }}<br/></p>
            <p><span>Genre</span><span id="colon">:</span>{{ song.Genre.Name }}</p>
        </div></a>
    {% endfor %}

    {% for artist in Artist %}
        <a href="{% url 'Detail' arg='a' id=artist.id%}"><div class="browse">
            <img src = "{{ artist.Picture.url }}" />

            <p>{{ artist.ArtistName }}</p><br/>

            <p>{{ artist.Bio |truncatechars:200  }}</p><br/>
        </div></a>
    {% endfor %}

    {% for genre in genres %}
        <a href="{% url 'Detail' arg='g' id=genre.id%}"><div class="browse">
            <img src = "{{ genre.Logo.url }}" />

            <p>{{ genre.Name }}<br/></p>

            <p>{{ genre.Details | truncatechars:200}}<br/></p>

        </div></a>
    {% endfor %}

    <button id="request_btn" onclick="document.getElementById('id01').style.display='block'">Make a Request</button>

    <div id="id01" class="modal">

    <form method='POST' class="modal-content animate" action="">{% csrf_token %}
    <div class="imgcontainer">
    <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
    </div>
    <div class="container">
        <label for="id_Song_name">Song name:</label>
        <input id="id_Song_name" maxlength="200" name="Song_name" type="text" required>
        <label for="id_Artist">Artist:</label>
        <input id="id_Artist" maxlength="100" name="Artist" type="text">
        <label for="id_Message">Message:</label><br/>
        <textarea cols="51" id="id_Message" name="Message" rows="10"></textarea>
        <button id="request_btn2" onclick="document.getElementById('id02')" type="submit">Submit</button>
        <button id="request_btn2" type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
    </div>
    </form>
    </div>

    <script>
    // Get the modal
    var modal = document.getElementById('id01');

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
    if (event.target === modal) {
    modal.style.display = "none";
    }
    }
    </script>
{% endif %}
<!--a href="{% url 'RequestForm' %}"><div>
    <p>Make a request</p>
</div></a-->
<footer>
    <!--Stuff for footer here-->
    <h1>Stay Connected</h1><h1>Music_Analysis Group Copyright &copy;2017 </h1>
    <div class="social-btns"><a class="btn facebook" href="#"><i class="fa fa-facebook"></i></a><a class="btn twitter" href="#"><i class="fa fa-twitter"></i></a><a class="btn google" href="#"><i class="fa fa-google"></i></a></div>

</footer>
</section>
</div>
</body>
</html>

templates/modal.html
<!DOCTYPE html>
<html>
<link rel="stylesheet" href="{% static "css/sg.css" %}">
<body>

<button onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Make a Request</button>

<div id="id01" class="modal">
  
  <form class="modal-content animate" action="">
    <div class="imgcontainer">
      <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
    </div>

    <div class="container">
      <label><b>Username</b></label>
      <input type="text" placeholder="Enter Username" name="uname" required>

      <label><b>Password</b></label>
      <input type="password" placeholder="Enter Password" name="psw" required>
        
      <button type="submit">Login</button>
      <input type="checkbox" checked="checked"> Remember me
    </div>

    <div class="container" style="background-color:#f1f1f1">
      <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
      <span class="psw">Forgot <a href="#">password?</a></span>
    </div>
  </form>
</div>

<script>
// Get the modal
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>

</body>
</html>